prompt:
check this file fully to get what is the problem with my deployment
if it's something related to the code. fix it by yourself 
if it's something related to adjustments in PythonAnyWhere configurations on the website
tell me here what to do
i provided all details in the file.
and provided my set info by the start of the file 

in pythinAnyWhere deploy
chapter 1: deploy process
this's the main page
Configuration for zeyadhoussainy.pythonanywhere.com
Reload:
Best before date:
We're happy to host your free website -- and keep it free -- for as long as you want to keep it running, but you'll need to log in at least once every three months and click the "Run until 3 months from today" button below. We'll send you an email a week before the site is disabled so that you don't forget to do that. See here for more details.

This site will be disabled on Sunday 30 November 2025

Paying users' sites stay up forever without any need to log in to keep them running.

Traffic:
How busy is your site?

This month (previous month)	35	(0)
Today (yesterday)	6	(28)
Hour (previous hour)	0	(0)
Want some more data? Paying accounts get pretty charts ;-)

Code:
What your site is running.

Source code:
/home/zeyadhoussainy/alx-BE-graduation-project-ECommerce

Go to directory
Working directory:
/home/zeyadhoussainy/

Go to directory
WSGI configuration file:/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py
Python version:
3.13
Virtualenv:
Use a virtualenv to get different versions of flask, django etc from our default system ones. More info here. You need to Reload your web app to activate it; NB - will do nothing if the virtualenv does not exist.

/home/zeyadhoussainy/venv

 Start a console in this virtualenv

Log files:
The first place to look if something goes wrong.

Access log:zeyadhoussainy.pythonanywhere.com.access.log
Error log:zeyadhoussainy.pythonanywhere.com.error.log
Server log:zeyadhoussainy.pythonanywhere.com.server.log
Log files are periodically rotated. You can find old logs here: /var/log

Static files:
Files that aren't dynamically generated by your code, like CSS, JavaScript or uploaded files, can be served much faster straight off the disk if you specify them here. You need to Reload your web app to activate any changes you make to the mappings below.

URL	Directory	Delete
Enter URL	Enter path	
Security:
An HTTPS certificate is needed so that people can access your site securely. We automatically provide a certificate for zeyadhoussainy.pythonanywhere.com.

HTTPS certificate:Automatically provided for this hostname
You need to Reload your web app to activate any changes made below.

Forcing HTTPS means that anyone who goes to your site using the insecure http URL will immediately be redirected to the secure https one. More information here.

Force HTTPS:
Password protection is ideal for sites that are under development when you don't want anyone to see them yet. Note that password length is effectively limited to 8 characters.

Password protection:
Username:Enter a username
Password:Enter a password


and this's thw WSGI config file:
import os
import sys

# Path to the folder where manage.py lives
path = '/home/zeyadhoussainy/alx-BE-graduation-project-ECommerce'
if path not in sys.path:
    sys.path.append(path)

# Point to your Django settings
os.environ['DJANGO_SETTINGS_MODULE'] = 'ecommerce_api.settings'

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()





chapter 2: the results of deploy
when i open https://zeyadhoussainy.pythonanywhere.com/ i get this message

Something went wrong :-(
Something went wrong while trying to load this website; please try again later.

If it is your site, you should check your logs to determine what the problem is.

There was an error loading your PythonAnywhere-hosted site. There may be a bug in your code.

Error code: Unhandled Exception

Debugging tips
The first place to look is at your web app page to ensure that there are no errors indicated there.
Next, check your site's server and error logs for any messages â€” you can view them here:
zeyadhoussainy.pythonanywhere.com.error.log
zeyadhoussainy.pythonanywhere.com.server.log
You can find helpful tips on the PythonAnywhere help site:
There's an ImportError in the logs
"403 Forbidden" error or "Connection Refused" error in logs
Database connection errors
There are many more helpful guides on our Help pages
If you get completely stuck, then drop us a line at PythonAnywhere Support <liveusercare@pythonanywhere.com>, in the forums, or using the "Send feedback" link on the site, with the relevant lines from your logs.

when i open zeyadhoussainy.pythonanywhere.com.error.log i get this message:
2025-08-30 21:29:17,820: Error running WSGI application
2025-08-30 21:29:17,828: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:29:17,828:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:29:17,828:     application = get_wsgi_application()
2025-08-30 21:29:17,828: 
2025-08-30 21:29:17,828:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:29:17,829:     django.setup(set_prefix=False)
2025-08-30 21:29:17,829:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:29:17,829: 
2025-08-30 21:29:17,829:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:29:17,829:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:29:17,829:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:29:17,829: 
2025-08-30 21:29:17,829:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:29:17,829:     self._setup(name)
2025-08-30 21:29:17,829:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:29:17,830: 
2025-08-30 21:29:17,830:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:29:17,830:     self._wrapped = Settings(settings_module)
2025-08-30 21:29:17,830:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:29:17,830: 
2025-08-30 21:29:17,830:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:29:17,830:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:29:17,830: ***************************************************
2025-08-30 21:29:17,831: If you're seeing an import error and don't know why,
2025-08-30 21:29:17,831: we have a dedicated help page to help you debug: 
2025-08-30 21:29:17,831: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:29:17,831: ***************************************************
2025-08-30 21:29:38,196: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:29:38,196:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:29:38,196:     application = get_wsgi_application()
2025-08-30 21:29:38,196: 
2025-08-30 21:29:38,196:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:29:38,197:     django.setup(set_prefix=False)
2025-08-30 21:29:38,197:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:29:38,197: 
2025-08-30 21:29:38,197:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:29:38,197:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:29:38,197:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:29:38,197: 
2025-08-30 21:29:38,197:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:29:38,197:     self._setup(name)
2025-08-30 21:29:38,197:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:29:38,197: 
2025-08-30 21:29:38,198:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:29:38,198:     self._wrapped = Settings(settings_module)
2025-08-30 21:29:38,198:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:29:38,198: 
2025-08-30 21:29:38,198:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:29:38,198:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:29:38,198: ***************************************************
2025-08-30 21:29:38,198: If you're seeing an import error and don't know why,
2025-08-30 21:29:38,198: we have a dedicated help page to help you debug: 
2025-08-30 21:29:38,198: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:29:38,199: ***************************************************
2025-08-30 21:33:13,006: Error running WSGI application
2025-08-30 21:33:13,013: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:33:13,014:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:33:13,014:     application = get_wsgi_application()
2025-08-30 21:33:13,014: 
2025-08-30 21:33:13,014:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:33:13,014:     django.setup(set_prefix=False)
2025-08-30 21:33:13,014:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:33:13,015: 
2025-08-30 21:33:13,015:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:33:13,015:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:33:13,015:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:33:13,015: 
2025-08-30 21:33:13,015:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:33:13,015:     self._setup(name)
2025-08-30 21:33:13,015:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:33:13,015: 
2025-08-30 21:33:13,015:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:33:13,015:     self._wrapped = Settings(settings_module)
2025-08-30 21:33:13,016:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:33:13,016: 
2025-08-30 21:33:13,016:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:33:13,016:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:33:13,016: ***************************************************
2025-08-30 21:33:13,016: If you're seeing an import error and don't know why,
2025-08-30 21:33:13,016: we have a dedicated help page to help you debug: 
2025-08-30 21:33:13,016: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:33:13,016: ***************************************************
2025-08-30 21:33:13,747: Error running WSGI application
2025-08-30 21:33:13,749: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:33:13,749:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:33:13,749:     application = get_wsgi_application()
2025-08-30 21:33:13,750: 
2025-08-30 21:33:13,750:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:33:13,750:     django.setup(set_prefix=False)
2025-08-30 21:33:13,750:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:33:13,750: 
2025-08-30 21:33:13,750:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:33:13,750:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:33:13,750:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:33:13,750: 
2025-08-30 21:33:13,750:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:33:13,751:     self._setup(name)
2025-08-30 21:33:13,751:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:33:13,751: 
2025-08-30 21:33:13,751:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:33:13,751:     self._wrapped = Settings(settings_module)
2025-08-30 21:33:13,751:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:33:13,751: 
2025-08-30 21:33:13,751:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:33:13,751:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:33:13,751: ***************************************************
2025-08-30 21:33:13,751: If you're seeing an import error and don't know why,
2025-08-30 21:33:13,752: we have a dedicated help page to help you debug: 
2025-08-30 21:33:13,752: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:33:13,752: ***************************************************
2025-08-30 21:33:15,193: Error running WSGI application
2025-08-30 21:33:15,195: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:33:15,195:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:33:15,195:     application = get_wsgi_application()
2025-08-30 21:33:15,195: 
2025-08-30 21:33:15,195:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:33:15,196:     django.setup(set_prefix=False)
2025-08-30 21:33:15,196:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:33:15,196: 
2025-08-30 21:33:15,196:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:33:15,196:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:33:15,196:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:33:15,196: 
2025-08-30 21:33:15,196:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:33:15,197:     self._setup(name)
2025-08-30 21:33:15,197:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:33:15,197: 
2025-08-30 21:33:15,197:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:33:15,197:     self._wrapped = Settings(settings_module)
2025-08-30 21:33:15,197:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:33:15,197: 
2025-08-30 21:33:15,198:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:33:15,198:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:33:15,198: ***************************************************
2025-08-30 21:33:15,198: If you're seeing an import error and don't know why,
2025-08-30 21:33:15,198: we have a dedicated help page to help you debug: 
2025-08-30 21:33:15,198: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:33:15,198: ***************************************************
2025-08-30 21:40:59,409: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:40:59,409:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:40:59,405: Error running WSGI application
2025-08-30 21:40:59,409:     application = get_wsgi_application()
2025-08-30 21:40:59,410: 
2025-08-30 21:40:59,410:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:40:59,410:     django.setup(set_prefix=False)
2025-08-30 21:40:59,410:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:40:59,410: 
2025-08-30 21:40:59,410:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:40:59,410:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:40:59,410:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:40:59,410: 
2025-08-30 21:40:59,411:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:40:59,411:     self._setup(name)
2025-08-30 21:40:59,411:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:40:59,411: 
2025-08-30 21:40:59,411:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:40:59,411:     self._wrapped = Settings(settings_module)
2025-08-30 21:40:59,411:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:40:59,411: 
2025-08-30 21:40:59,412:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:40:59,412:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:40:59,412: ***************************************************
2025-08-30 21:40:59,412: If you're seeing an import error and don't know why,
2025-08-30 21:40:59,412: we have a dedicated help page to help you debug: 
2025-08-30 21:40:59,412: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:40:59,412: ***************************************************
2025-08-30 21:41:01,206: Error running WSGI application
2025-08-30 21:41:01,208:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:41:01,208:     application = get_wsgi_application()
2025-08-30 21:41:01,209: 
2025-08-30 21:41:01,209:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:41:01,209:     django.setup(set_prefix=False)
2025-08-30 21:41:01,209:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:41:01,209: 
2025-08-30 21:41:01,209:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:41:01,209:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:41:01,209:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:41:01,209: 
2025-08-30 21:41:01,210:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:41:01,210:     self._setup(name)
2025-08-30 21:41:01,210:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:41:01,210: 
2025-08-30 21:41:01,210:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:41:01,210:     self._wrapped = Settings(settings_module)
2025-08-30 21:41:01,210:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:41:01,210: 
2025-08-30 21:41:01,210:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:41:01,210:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:41:01,211: ***************************************************
2025-08-30 21:41:01,211: If you're seeing an import error and don't know why,
2025-08-30 21:41:01,211: we have a dedicated help page to help you debug: 
2025-08-30 21:41:01,211: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:41:01,211: ***************************************************
2025-08-30 21:41:01,208: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:47:05,190: Error running WSGI application
2025-08-30 21:47:05,205: ModuleNotFoundError: No module named 'alx-BE-graduation-project-ECommerce.settings'
2025-08-30 21:47:05,205:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:47:05,205:     application = get_wsgi_application()
2025-08-30 21:47:05,205: 
2025-08-30 21:47:05,205:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:47:05,205:     django.setup(set_prefix=False)
2025-08-30 21:47:05,206:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:47:05,206: 
2025-08-30 21:47:05,206:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 19, in setup
2025-08-30 21:47:05,207:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2025-08-30 21:47:05,207:                       ^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:47:05,207: 
2025-08-30 21:47:05,207:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
2025-08-30 21:47:05,208:     self._setup(name)
2025-08-30 21:47:05,208:     ~~~~~~~~~~~^^^^^^
2025-08-30 21:47:05,208: 
2025-08-30 21:47:05,209:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
2025-08-30 21:47:05,209:     self._wrapped = Settings(settings_module)
2025-08-30 21:47:05,209:                     ~~~~~~~~^^^^^^^^^^^^^^^^^
2025-08-30 21:47:05,209: 
2025-08-30 21:47:05,209:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
2025-08-30 21:47:05,209:     mod = importlib.import_module(self.SETTINGS_MODULE)
2025-08-30 21:47:05,209: ***************************************************
2025-08-30 21:47:05,210: If you're seeing an import error and don't know why,
2025-08-30 21:47:05,210: we have a dedicated help page to help you debug: 
2025-08-30 21:47:05,210: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:47:05,210: ***************************************************
2025-08-30 21:47:21,956: Error running WSGI application
2025-08-30 21:47:21,967: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 21:47:21,967:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:47:21,968:     application = get_wsgi_application()
2025-08-30 21:47:21,968:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:47:21,968:     django.setup(set_prefix=False)
2025-08-30 21:47:21,968:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:47:21,969: 
2025-08-30 21:47:21,969:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 21:47:21,969:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 21:47:21,969:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:47:21,969: 
2025-08-30 21:47:21,970:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 21:47:21,970:     app_config = AppConfig.create(entry)
2025-08-30 21:47:21,970:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 21:47:21,970: 
2025-08-30 21:47:21,970:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 21:47:21,971:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 21:47:21,971: ***************************************************
2025-08-30 21:47:21,971: If you're seeing an import error and don't know why,
2025-08-30 21:47:24,041: Error running WSGI application
2025-08-30 21:47:24,046: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 21:47:24,046:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:47:24,047:     application = get_wsgi_application()
2025-08-30 21:47:24,049: ***************************************************
2025-08-30 21:47:25,154: Error running WSGI application
2025-08-30 21:47:25,157: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 21:47:25,157:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:47:25,157:     application = get_wsgi_application()
2025-08-30 21:47:25,157: 
2025-08-30 21:47:25,157:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:47:25,158:     django.setup(set_prefix=False)
2025-08-30 21:47:25,158:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:47:25,158: 
2025-08-30 21:47:25,158:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 21:47:25,158:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 21:47:25,158:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:47:25,158: 
2025-08-30 21:47:25,159:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 21:47:25,159:     app_config = AppConfig.create(entry)
2025-08-30 21:47:25,159: 
2025-08-30 21:47:25,159:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 21:47:25,159:     import_module(entry)
2025-08-30 21:47:25,159:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 21:47:25,159: 
2025-08-30 21:47:25,159:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 21:47:25,159:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 21:47:25,160: ***************************************************
2025-08-30 21:47:25,160: If you're seeing an import error and don't know why,
2025-08-30 21:47:25,160: we have a dedicated help page to help you debug: 
2025-08-30 21:47:25,160: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:47:25,160: ***************************************************
2025-08-30 21:59:08,175: Error running WSGI application
2025-08-30 21:59:08,183: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 21:59:08,184:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 21:59:08,184:     application = get_wsgi_application()
2025-08-30 21:59:08,184: 
2025-08-30 21:59:08,184:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 21:59:08,184:     django.setup(set_prefix=False)
2025-08-30 21:59:08,184:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 21:59:08,184: 
2025-08-30 21:59:08,184:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 21:59:08,184:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 21:59:08,185:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 21:59:08,185: 
2025-08-30 21:59:08,185:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 21:59:08,185:     app_config = AppConfig.create(entry)
2025-08-30 21:59:08,185: 
2025-08-30 21:59:08,185:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 21:59:08,185:     import_module(entry)
2025-08-30 21:59:08,185:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 21:59:08,185: 
2025-08-30 21:59:08,185:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 21:59:08,186:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 21:59:08,186: ***************************************************
2025-08-30 21:59:08,186: If you're seeing an import error and don't know why,
2025-08-30 21:59:08,186: we have a dedicated help page to help you debug: 
2025-08-30 21:59:08,186: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 21:59:08,186: ***************************************************
2025-08-30 22:05:46,003: Error running WSGI application
2025-08-30 22:05:46,005: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 22:05:46,005:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 22:05:46,006:     application = get_wsgi_application()
2025-08-30 22:05:46,006: 
2025-08-30 22:05:46,006:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 22:05:46,006:     django.setup(set_prefix=False)
2025-08-30 22:05:46,006:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 22:05:46,006: 
2025-08-30 22:05:46,006:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 22:05:46,006:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 22:05:46,007:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 22:05:46,007: 
2025-08-30 22:05:46,007:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 22:05:46,007:     app_config = AppConfig.create(entry)
2025-08-30 22:05:46,007: 
2025-08-30 22:05:46,007:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 22:05:46,007:     import_module(entry)
2025-08-30 22:05:46,007:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 22:05:46,007: 
2025-08-30 22:05:46,007:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 22:05:46,008:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 22:05:46,008: ***************************************************
2025-08-30 22:05:46,008: If you're seeing an import error and don't know why,
2025-08-30 22:05:46,008: we have a dedicated help page to help you debug: 
2025-08-30 22:05:46,008: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 22:05:46,008: ***************************************************
2025-08-30 22:05:47,131: Error running WSGI application
2025-08-30 22:05:47,135: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 22:05:47,135:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 22:05:47,135:     application = get_wsgi_application()
2025-08-30 22:05:47,136: 
2025-08-30 22:05:47,136:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 22:05:47,136:     django.setup(set_prefix=False)
2025-08-30 22:05:47,136:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 22:05:47,136: 
2025-08-30 22:05:47,136:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 22:05:47,137:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 22:05:47,137:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 22:05:47,137: 
2025-08-30 22:05:47,137:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 22:05:47,137:     app_config = AppConfig.create(entry)
2025-08-30 22:05:47,137: 
2025-08-30 22:05:47,138:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 22:05:47,138:     import_module(entry)
2025-08-30 22:05:47,138:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 22:05:47,138: 
2025-08-30 22:05:47,138:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 22:05:47,138:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 22:05:47,138: ***************************************************
2025-08-30 22:05:47,138: If you're seeing an import error and don't know why,
2025-08-30 22:05:47,139: we have a dedicated help page to help you debug: 
2025-08-30 22:05:47,139: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 22:05:47,139: ***************************************************
2025-08-30 22:08:05,616: Error running WSGI application
2025-08-30 22:08:05,624: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 22:08:05,624:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 48, in <module>
2025-08-30 22:08:05,625:     application = get_wsgi_application()
2025-08-30 22:08:05,625: 
2025-08-30 22:08:05,625:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 22:08:05,625:     django.setup(set_prefix=False)
2025-08-30 22:08:05,625:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 22:08:05,625: 
2025-08-30 22:08:05,626:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 22:08:05,626:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 22:08:05,626:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 22:08:05,626: 
2025-08-30 22:08:05,626:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 22:08:05,626:     app_config = AppConfig.create(entry)
2025-08-30 22:08:05,626: 
2025-08-30 22:08:05,626:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 22:08:05,626:     import_module(entry)
2025-08-30 22:08:05,626:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 22:08:05,626: 
2025-08-30 22:08:05,627:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 22:08:05,627:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 22:08:05,627: ***************************************************
2025-08-30 22:08:05,627: If you're seeing an import error and don't know why,
2025-08-30 22:08:05,627: we have a dedicated help page to help you debug: 
2025-08-30 22:08:05,627: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 22:08:05,627: ***************************************************
2025-08-30 22:28:00,124: Error running WSGI application
2025-08-30 22:29:02,490: Error running WSGI application
2025-08-30 22:29:02,498: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 22:29:02,498:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-30 22:29:02,498:     application = get_wsgi_application()
2025-08-30 22:29:02,498: 
2025-08-30 22:29:02,498:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 22:29:02,499:     django.setup(set_prefix=False)
2025-08-30 22:29:02,499:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 22:29:02,499: 
2025-08-30 22:29:02,499:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 22:29:02,499:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 22:29:02,499:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 22:29:02,499: 
2025-08-30 22:29:02,499:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 22:29:02,499:     app_config = AppConfig.create(entry)
2025-08-30 22:29:02,499: 
2025-08-30 22:29:02,499:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 22:29:02,500:     import_module(entry)
2025-08-30 22:29:02,500:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 22:29:02,500: 
2025-08-30 22:29:02,500:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 22:29:02,500:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 22:29:02,500: ***************************************************
2025-08-30 22:29:02,500: If you're seeing an import error and don't know why,
2025-08-30 22:29:02,500: we have a dedicated help page to help you debug: 
2025-08-30 22:29:02,500: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 22:29:02,500: ***************************************************
2025-08-30 22:44:34,931: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 22:44:34,931:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-30 22:44:34,931:     application = get_wsgi_application()
2025-08-30 22:44:34,931: 
2025-08-30 22:44:34,931:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 22:44:34,931:     django.setup(set_prefix=False)
2025-08-30 22:44:34,932:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 22:44:34,932: 
2025-08-30 22:44:34,932:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 22:44:34,932:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 22:44:34,932:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 22:44:34,932: 
2025-08-30 22:44:34,932:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 22:44:34,932:     app_config = AppConfig.create(entry)
2025-08-30 22:44:34,932: 
2025-08-30 22:44:34,933:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 22:44:34,933:     import_module(entry)
2025-08-30 22:44:34,933:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 22:44:34,933: 
2025-08-30 22:44:34,933:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 22:44:34,933:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 22:44:34,933: ***************************************************
2025-08-30 22:44:34,933: If you're seeing an import error and don't know why,
2025-08-30 22:44:34,933: we have a dedicated help page to help you debug: 
2025-08-30 22:44:34,933: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 22:44:36,411: Error running WSGI application
2025-08-30 22:44:36,413: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 22:44:36,413:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-30 22:44:36,413:     application = get_wsgi_application()
2025-08-30 22:44:36,414: 
2025-08-30 22:44:36,414:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 22:44:36,414:     django.setup(set_prefix=False)
2025-08-30 22:44:36,414:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 22:44:36,414: 
2025-08-30 22:44:36,414:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 22:44:36,414:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 22:44:36,414:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-30 22:44:36,414: 
2025-08-30 22:44:36,414:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 22:44:36,415:     app_config = AppConfig.create(entry)
2025-08-30 22:44:36,415: 
2025-08-30 22:44:36,415:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 22:44:36,415:     import_module(entry)
2025-08-30 22:44:36,415:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 22:44:36,415: 
2025-08-30 22:44:36,415:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 22:44:36,415:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 22:44:36,415: ***************************************************
2025-08-30 22:44:36,415: If you're seeing an import error and don't know why,
2025-08-30 22:44:36,415: we have a dedicated help page to help you debug: 
2025-08-30 22:44:36,416: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 22:44:36,416: ***************************************************
2025-08-30 22:48:53,742: 
2025-08-30 22:48:53,742:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-30 22:48:53,742:     app_config = AppConfig.create(entry)
2025-08-30 22:48:53,742: 
2025-08-30 22:48:53,742:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-30 22:48:53,742:     import_module(entry)
2025-08-30 22:48:53,742:     ~~~~~~~~~~~~~^^^^^^^
2025-08-30 22:48:53,743: 
2025-08-30 22:48:53,743:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-30 22:48:53,743:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-30 22:48:53,743: ***************************************************
2025-08-30 22:48:53,743: If you're seeing an import error and don't know why,
2025-08-30 22:48:53,743: we have a dedicated help page to help you debug: 
2025-08-30 22:48:53,743: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-30 22:48:53,743: ***************************************************
2025-08-30 22:48:53,738: Error running WSGI application
2025-08-30 22:48:53,741: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-30 22:48:53,741:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-30 22:48:53,741:     application = get_wsgi_application()
2025-08-30 22:48:53,741: 
2025-08-30 22:48:53,741:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-30 22:48:53,741:     django.setup(set_prefix=False)
2025-08-30 22:48:53,742:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-30 22:48:53,742: 
2025-08-30 22:48:53,742:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-30 22:48:53,742:     apps.populate(settings.INSTALLED_APPS)
2025-08-30 22:48:53,742:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 07:28:12,211: Error running WSGI application
2025-08-31 07:28:12,277: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 07:28:12,278:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 07:28:12,279:     application = get_wsgi_application()
2025-08-31 07:28:12,279: 
2025-08-31 07:28:12,279:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 07:28:12,279:     django.setup(set_prefix=False)
2025-08-31 07:28:12,280:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 07:28:12,280: 
2025-08-31 07:28:12,280:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 07:28:12,280:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 07:28:12,280:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 07:28:12,281: 
2025-08-31 07:28:12,281:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 07:28:12,281:     app_config = AppConfig.create(entry)
2025-08-31 07:28:12,281: 
2025-08-31 07:28:12,282:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 07:28:12,282:     import_module(entry)
2025-08-31 07:28:12,282:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 07:28:12,283: 
2025-08-31 07:28:12,283:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 07:28:12,283:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 07:28:12,283: ***************************************************
2025-08-31 07:28:12,284: If you're seeing an import error and don't know why,
2025-08-31 07:28:12,284: we have a dedicated help page to help you debug: 
2025-08-31 07:28:12,284: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 07:28:12,284: ***************************************************
2025-08-31 07:32:10,822: Error running WSGI application
2025-08-31 07:32:10,829: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 07:32:10,829:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 07:32:10,829:     application = get_wsgi_application()
2025-08-31 07:32:10,830: 
2025-08-31 07:32:10,830:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 07:32:10,830:     django.setup(set_prefix=False)
2025-08-31 07:32:10,830:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 07:32:10,831: 
2025-08-31 07:32:10,831:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 07:32:10,831:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 07:32:10,832:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 07:32:10,832: 
2025-08-31 07:32:10,833:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 07:32:10,833:     app_config = AppConfig.create(entry)
2025-08-31 07:32:10,833: 
2025-08-31 07:32:10,833:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 07:32:10,833:     import_module(entry)
2025-08-31 07:32:10,834:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 07:32:10,834: 
2025-08-31 07:32:10,834:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 07:32:10,834:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 07:32:10,834: ***************************************************
2025-08-31 07:32:10,835: If you're seeing an import error and don't know why,
2025-08-31 07:32:10,835: we have a dedicated help page to help you debug: 
2025-08-31 07:32:10,835: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 07:32:10,835: ***************************************************
2025-08-31 07:32:12,471: Error running WSGI application
2025-08-31 07:32:12,473: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 07:32:12,473:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 07:32:12,473:     application = get_wsgi_application()
2025-08-31 07:32:12,474: 
2025-08-31 07:32:12,474:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 07:32:12,474:     django.setup(set_prefix=False)
2025-08-31 07:32:12,474:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 07:32:12,475: 
2025-08-31 07:32:12,475:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 07:32:12,475:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 07:32:12,475:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 07:32:12,475: 
2025-08-31 07:32:12,476:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 07:32:12,476:     app_config = AppConfig.create(entry)
2025-08-31 07:32:12,477: 
2025-08-31 07:32:12,477:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 07:32:12,477:     import_module(entry)
2025-08-31 07:32:12,477:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 07:32:12,478: 
2025-08-31 07:32:12,478:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 07:32:12,478:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 07:32:12,478: ***************************************************
2025-08-31 07:32:12,479: If you're seeing an import error and don't know why,
2025-08-31 07:32:12,479: we have a dedicated help page to help you debug: 
2025-08-31 07:32:12,479: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 07:32:12,479: ***************************************************
2025-08-31 07:38:13,135: Error running WSGI application
2025-08-31 07:38:13,150: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 07:38:13,151:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 07:38:13,151:     application = get_wsgi_application()
2025-08-31 07:38:13,151: 
2025-08-31 07:38:13,151:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 07:38:13,151:     django.setup(set_prefix=False)
2025-08-31 07:38:13,151:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 07:38:13,152: 
2025-08-31 07:38:13,152:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 07:38:13,152:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 07:38:13,152:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 07:38:13,152: 
2025-08-31 07:38:13,153:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 07:38:13,153:     app_config = AppConfig.create(entry)
2025-08-31 07:38:13,153: 
2025-08-31 07:38:13,153:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 07:38:13,153:     import_module(entry)
2025-08-31 07:38:13,153:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 07:38:13,153: 
2025-08-31 07:38:13,154:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 07:38:13,154:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 07:38:13,154: ***************************************************
2025-08-31 07:38:13,154: If you're seeing an import error and don't know why,
2025-08-31 07:38:13,154: we have a dedicated help page to help you debug: 
2025-08-31 07:38:13,154: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 07:38:13,154: ***************************************************
2025-08-31 07:38:22,270: Error running WSGI application
2025-08-31 07:38:22,273: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 07:38:22,273:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 07:38:22,274:     application = get_wsgi_application()
2025-08-31 07:38:22,274: 
2025-08-31 07:38:22,274:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 07:38:22,274:     django.setup(set_prefix=False)
2025-08-31 07:38:22,275:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 07:38:22,275: 
2025-08-31 07:38:22,275:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 07:38:22,275:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 07:38:22,275:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 07:38:22,275: 
2025-08-31 07:38:22,275:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 07:38:22,276:     app_config = AppConfig.create(entry)
2025-08-31 07:38:22,276: 
2025-08-31 07:38:22,276:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 07:38:22,276:     import_module(entry)
2025-08-31 07:38:22,276:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 07:38:22,276: 
2025-08-31 07:38:22,276:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 07:38:22,277:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 07:38:22,277: ***************************************************
2025-08-31 07:38:22,277: If you're seeing an import error and don't know why,
2025-08-31 07:38:22,277: we have a dedicated help page to help you debug: 
2025-08-31 07:38:22,277: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 07:38:22,277: ***************************************************
2025-08-31 07:38:23,472: Error running WSGI application
2025-08-31 07:38:23,473: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 07:38:23,474:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 07:38:23,474:     application = get_wsgi_application()
2025-08-31 07:38:23,474: 
2025-08-31 07:38:23,474:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 07:38:23,474:     django.setup(set_prefix=False)
2025-08-31 07:38:23,474:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 07:38:23,474: 
2025-08-31 07:38:23,474:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 07:38:23,475:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 07:38:23,475:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 07:38:23,475: 
2025-08-31 07:38:23,475:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 07:38:23,475:     app_config = AppConfig.create(entry)
2025-08-31 07:38:23,475: 
2025-08-31 07:38:23,475:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 07:38:23,475:     import_module(entry)
2025-08-31 07:38:23,475:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 07:38:23,475: 
2025-08-31 07:38:23,476:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 07:38:23,476:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 07:38:23,476: ***************************************************
2025-08-31 07:38:23,476: If you're seeing an import error and don't know why,
2025-08-31 07:38:23,476: we have a dedicated help page to help you debug: 
2025-08-31 07:38:23,476: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 07:38:23,476: ***************************************************
2025-08-31 21:24:39,858: Error running WSGI application
2025-08-31 21:24:39,861: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 21:24:39,861:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 21:24:39,861:     application = get_wsgi_application()
2025-08-31 21:24:39,861: 
2025-08-31 21:24:39,861:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 21:24:39,861:     django.setup(set_prefix=False)
2025-08-31 21:24:39,861:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 21:24:39,862: 
2025-08-31 21:24:39,862:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 21:24:39,862:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 21:24:39,862:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 21:24:39,862: 
2025-08-31 21:24:39,862:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 21:24:39,862:     app_config = AppConfig.create(entry)
2025-08-31 21:24:39,862: 
2025-08-31 21:24:39,863:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 21:24:39,863:     import_module(entry)
2025-08-31 21:24:39,863:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 21:24:39,863: 
2025-08-31 21:24:39,863:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 21:24:39,863:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 21:24:39,863: ***************************************************
2025-08-31 21:24:39,863: If you're seeing an import error and don't know why,
2025-08-31 21:24:39,863: we have a dedicated help page to help you debug: 
2025-08-31 21:24:39,863: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 21:24:39,863: ***************************************************
2025-08-31 21:24:41,462: Error running WSGI application
2025-08-31 21:24:41,464: ModuleNotFoundError: No module named 'pkg_resources'
2025-08-31 21:24:41,464:   File "/var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py", line 13, in <module>
2025-08-31 21:24:41,464:     application = get_wsgi_application()
2025-08-31 21:24:41,465: 
2025-08-31 21:24:41,465:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-08-31 21:24:41,465:     django.setup(set_prefix=False)
2025-08-31 21:24:41,465:     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-08-31 21:24:41,465: 
2025-08-31 21:24:41,465:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-08-31 21:24:41,465:     apps.populate(settings.INSTALLED_APPS)
2025-08-31 21:24:41,465:     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-31 21:24:41,465: 
2025-08-31 21:24:41,466:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/registry.py", line 91, in populate
2025-08-31 21:24:41,466:     app_config = AppConfig.create(entry)
2025-08-31 21:24:41,466: 
2025-08-31 21:24:41,466:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/django/apps/config.py", line 193, in create
2025-08-31 21:24:41,466:     import_module(entry)
2025-08-31 21:24:41,466:     ~~~~~~~~~~~~~^^^^^^^
2025-08-31 21:24:41,466: 
2025-08-31 21:24:41,466:   File "/home/zeyadhoussainy/venv/lib/python3.13/site-packages/rest_framework_simplejwt/__init__.py", line 1, in <module>
2025-08-31 21:24:41,467:     from pkg_resources import DistributionNotFound, get_distribution
2025-08-31 21:24:41,467: ***************************************************
2025-08-31 21:24:41,467: If you're seeing an import error and don't know why,
2025-08-31 21:24:41,467: we have a dedicated help page to help you debug: 
2025-08-31 21:24:41,467: https://help.pythonanywhere.com/pages/DebuggingImportError/
2025-08-31 21:24:41,467: ***************************************************


and when i open zeyadhoussainy.pythonanywhere.com.server.log i get these message
2025-08-19 20:39:45 *** Starting uWSGI 2.0.28 (64bit) on [Tue Aug 19 20:39:44 2025] ***
2025-08-19 20:39:45 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-19 20:39:45 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-19 20:39:45 nodename: green-liveweb38
2025-08-19 20:39:45 machine: x86_64
2025-08-19 20:39:45 clock source: unix
2025-08-19 20:39:45 pcre jit disabled
2025-08-19 20:39:45 detected number of CPU cores: 4
2025-08-19 20:39:45 current working directory: /home/zeyadhoussainy
2025-08-19 20:39:45 detected binary path: /usr/local/bin/uwsgi
2025-08-19 20:39:45 *** dumping internal routing table ***
2025-08-19 20:39:45 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-19 20:39:45 *** end of the internal routing table ***
2025-08-19 20:39:45 chdir() to /home/zeyadhoussainy/
2025-08-19 20:39:45 your processes number limit is 256
2025-08-19 20:39:45 your memory page size is 4096 bytes
2025-08-19 20:39:45 detected max file descriptor number: 123456
2025-08-19 20:39:45 building mime-types dictionary from file /etc/mime.types...
2025-08-19 20:39:45 1516 entry found
2025-08-19 20:39:45 lock engine: pthread robust mutexes
2025-08-19 20:39:45 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-19 20:39:45 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-19 20:39:45 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-19 20:39:45 Python main interpreter initialized at 0x75a932b90ab0
2025-08-19 20:39:45 python threads support enabled
2025-08-19 20:39:45 your server socket listen backlog is limited to 100 connections
2025-08-19 20:39:45 your mercy for graceful operations on workers is 60 seconds
2025-08-19 20:39:45 setting request body buffering size to 65536 bytes
2025-08-19 20:39:45 mapped 334256 bytes (326 KB) for 1 cores
2025-08-19 20:39:45 *** Operational MODE: single process ***
2025-08-19 20:39:45 initialized 38 metrics
2025-08-19 20:39:45 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x75a932b90ab0 pid: 1 (default app)
2025-08-19 20:39:45 *** uWSGI is running in multiple interpreter mode ***
2025-08-19 20:39:45 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-19 20:39:45 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-19 20:39:45 metrics collector thread started
2025-08-19 20:39:45 spawned 2 offload threads for uWSGI worker 1
2025-08-30 20:27:18 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 20:27:17 2025] ***
2025-08-30 20:27:18 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 20:27:18 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 20:27:18 nodename: green-liveweb35
2025-08-30 20:27:18 machine: x86_64
2025-08-30 20:27:18 clock source: unix
2025-08-30 20:27:18 pcre jit disabled
2025-08-30 20:27:18 detected number of CPU cores: 4
2025-08-30 20:27:18 current working directory: /home/zeyadhoussainy
2025-08-30 20:27:18 detected binary path: /usr/local/bin/uwsgi
2025-08-30 20:27:18 *** dumping internal routing table ***
2025-08-30 20:27:18 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 20:27:18 *** end of the internal routing table ***
2025-08-30 20:27:18 chdir() to /home/zeyadhoussainy/
2025-08-30 20:27:18 your processes number limit is 256
2025-08-30 20:27:18 your memory page size is 4096 bytes
2025-08-30 20:27:18 detected max file descriptor number: 123456
2025-08-30 20:27:18 building mime-types dictionary from file /etc/mime.types...
2025-08-30 20:27:18 1516 entry found
2025-08-30 20:27:18 lock engine: pthread robust mutexes
2025-08-30 20:27:18 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 20:27:18 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 20:27:18 Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
2025-08-30 20:27:18 Python main interpreter initialized at 0x6172979aa8d0
2025-08-30 20:27:18 python threads support enabled
2025-08-30 20:27:18 your server socket listen backlog is limited to 100 connections
2025-08-30 20:27:18 your mercy for graceful operations on workers is 60 seconds
2025-08-30 20:27:18 setting request body buffering size to 65536 bytes
2025-08-30 20:27:18 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 20:27:18 *** Operational MODE: single process ***
2025-08-30 20:27:18 initialized 38 metrics
2025-08-30 20:27:18 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x6172979aa8d0 pid: 1 (default app)
2025-08-30 20:27:18 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 20:27:18 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 20:27:18 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 20:27:18 metrics collector thread started
2025-08-30 20:27:18 spawned 2 offload threads for uWSGI worker 1
2025-08-30 20:27:19 announcing my loyalty to the Emperor...
2025-08-30 20:34:34 Sat Aug 30 20:34:34 2025 - *** /etc/uwsgi/zeyadhoussainy.pythonanywhere.com.ini has been touched... grace them all !!! ***
2025-08-30 20:34:34 ...gracefully killing workers...
2025-08-30 20:34:34 Gracefully killing worker 1 (pid: 2)...
2025-08-30 20:34:45 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 20:34:44 2025] ***
2025-08-30 20:34:45 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 20:34:45 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 20:34:45 nodename: green-liveweb41
2025-08-30 20:34:45 machine: x86_64
2025-08-30 20:34:45 clock source: unix
2025-08-30 20:34:45 pcre jit disabled
2025-08-30 20:34:45 detected number of CPU cores: 4
2025-08-30 20:34:45 current working directory: /home/zeyadhoussainy
2025-08-30 20:34:45 detected binary path: /usr/local/bin/uwsgi
2025-08-30 20:34:45 *** dumping internal routing table ***
2025-08-30 20:34:45 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 20:34:45 *** end of the internal routing table ***
2025-08-30 20:34:45 chdir() to /home/zeyadhoussainy/
2025-08-30 20:34:45 your processes number limit is 256
2025-08-30 20:34:45 your memory page size is 4096 bytes
2025-08-30 20:34:45 detected max file descriptor number: 123456
2025-08-30 20:34:45 building mime-types dictionary from file /etc/mime.types...
2025-08-30 20:34:45 1516 entry found
2025-08-30 20:34:45 lock engine: pthread robust mutexes
2025-08-30 20:34:45 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 20:34:45 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 20:34:45 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 20:34:45 Python main interpreter initialized at 0x7d3a389a4ab0
2025-08-30 20:34:45 python threads support enabled
2025-08-30 20:34:45 your server socket listen backlog is limited to 100 connections
2025-08-30 20:34:45 your mercy for graceful operations on workers is 60 seconds
2025-08-30 20:34:45 setting request body buffering size to 65536 bytes
2025-08-30 20:34:45 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 20:34:45 *** Operational MODE: single process ***
2025-08-30 20:34:45 initialized 38 metrics
2025-08-30 20:34:45 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7d3a389a4ab0 pid: 1 (default app)
2025-08-30 20:34:45 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 20:34:45 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 20:34:45 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 20:34:45 metrics collector thread started
2025-08-30 20:34:45 spawned 2 offload threads for uWSGI worker 1
2025-08-30 20:34:46 announcing my loyalty to the Emperor...
2025-08-30 21:29:17 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:29:16 2025] ***
2025-08-30 21:29:17 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:29:17 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:29:17 nodename: green-liveweb41
2025-08-30 21:29:17 machine: x86_64
2025-08-30 21:29:17 clock source: unix
2025-08-30 21:29:17 pcre jit disabled
2025-08-30 21:29:17 detected number of CPU cores: 4
2025-08-30 21:29:17 current working directory: /home/zeyadhoussainy
2025-08-30 21:29:17 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:29:17 *** dumping internal routing table ***
2025-08-30 21:29:17 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:29:17 *** end of the internal routing table ***
2025-08-30 21:29:17 chdir() to /home/zeyadhoussainy/
2025-08-30 21:29:17 your processes number limit is 256
2025-08-30 21:29:17 your memory page size is 4096 bytes
2025-08-30 21:29:17 detected max file descriptor number: 123456
2025-08-30 21:29:17 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:29:17 1516 entry found
2025-08-30 21:29:17 lock engine: pthread robust mutexes
2025-08-30 21:29:17 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:29:17 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 21:29:17 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:29:17 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:29:17 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:29:17 Python main interpreter initialized at 0x7bca1400eab0
2025-08-30 21:29:17 python threads support enabled
2025-08-30 21:29:17 your server socket listen backlog is limited to 100 connections
2025-08-30 21:29:17 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:29:17 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:29:17 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 21:29:17 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 21:29:17 metrics collector thread started
2025-08-30 21:29:17 spawned 2 offload threads for uWSGI worker 1
2025-08-30 21:29:17 announcing my loyalty to the Emperor...
2025-08-30 21:29:31 Sat Aug 30 21:29:31 2025 - received message 0 from emperor
2025-08-30 21:29:31 SIGINT/SIGTERM received...killing workers...
2025-08-30 21:29:32 worker 1 buried after 1 seconds
2025-08-30 21:29:32 goodbye to uWSGI.
2025-08-30 21:29:32 VACUUM: unix socket /var/sockets/zeyadhoussainy.pythonanywhere.com/socket removed.
2025-08-30 21:29:37 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:29:36 2025] ***
2025-08-30 21:29:37 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:29:37 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:29:37 nodename: green-liveweb41
2025-08-30 21:29:37 machine: x86_64
2025-08-30 21:29:37 clock source: unix
2025-08-30 21:29:37 pcre jit disabled
2025-08-30 21:29:37 detected number of CPU cores: 4
2025-08-30 21:29:37 current working directory: /home/zeyadhoussainy
2025-08-30 21:29:37 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:29:37 *** dumping internal routing table ***
2025-08-30 21:29:37 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:29:37 *** end of the internal routing table ***
2025-08-30 21:29:37 chdir() to /home/zeyadhoussainy/
2025-08-30 21:29:37 your processes number limit is 256
2025-08-30 21:29:37 your memory page size is 4096 bytes
2025-08-30 21:29:37 detected max file descriptor number: 123456
2025-08-30 21:29:37 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:29:37 1516 entry found
2025-08-30 21:29:37 lock engine: pthread robust mutexes
2025-08-30 21:29:37 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:29:37 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 21:29:37 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:29:37 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:29:37 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:29:37 Python main interpreter initialized at 0x7629d68c2ab0
2025-08-30 21:29:37 python threads support enabled
2025-08-30 21:29:37 your server socket listen backlog is limited to 100 connections
2025-08-30 21:29:37 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:29:37 setting request body buffering size to 65536 bytes
2025-08-30 21:29:37 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 21:29:37 *** Operational MODE: single process ***
2025-08-30 21:29:37 initialized 38 metrics
2025-08-30 21:29:37 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7629d68c2ab0 pid: 1 (default app)
2025-08-30 21:29:37 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:29:37 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 21:29:37 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 21:29:37 metrics collector thread started
2025-08-30 21:29:38 announcing my loyalty to the Emperor...
2025-08-30 21:33:02 Sat Aug 30 21:33:02 2025 - received message 0 from emperor
2025-08-30 21:33:02 SIGINT/SIGTERM received...killing workers...
2025-08-30 21:33:09 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:33:08 2025] ***
2025-08-30 21:33:09 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:33:09 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:33:13 announcing my loyalty to the Emperor...
2025-08-30 21:33:09 nodename: green-liveweb41
2025-08-30 21:33:09 machine: x86_64
2025-08-30 21:33:09 clock source: unix
2025-08-30 21:33:09 pcre jit disabled
2025-08-30 21:33:09 detected number of CPU cores: 4
2025-08-30 21:33:09 current working directory: /home/zeyadhoussainy
2025-08-30 21:33:09 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:33:09 *** dumping internal routing table ***
2025-08-30 21:33:09 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:33:09 *** end of the internal routing table ***
2025-08-30 21:33:09 chdir() to /home/zeyadhoussainy/
2025-08-30 21:33:09 your processes number limit is 256
2025-08-30 21:33:09 your memory page size is 4096 bytes
2025-08-30 21:33:09 detected max file descriptor number: 123456
2025-08-30 21:33:09 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:33:09 1516 entry found
2025-08-30 21:33:09 lock engine: pthread robust mutexes
2025-08-30 21:33:09 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:33:09 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 21:33:09 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:33:09 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:33:09 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:33:09 Python main interpreter initialized at 0x75f6249b0ab0
2025-08-30 21:33:09 python threads support enabled
2025-08-30 21:33:09 your server socket listen backlog is limited to 100 connections
2025-08-30 21:33:09 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:33:09 setting request body buffering size to 65536 bytes
2025-08-30 21:33:09 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 21:33:09 *** Operational MODE: single process ***
2025-08-30 21:33:09 initialized 38 metrics
2025-08-30 21:33:09 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x75f6249b0ab0 pid: 1 (default app)
2025-08-30 21:33:09 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:33:09 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 21:33:09 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 21:33:09 metrics collector thread started
2025-08-30 21:33:09 spawned 2 offload threads for uWSGI worker 1
2025-08-30 21:46:58 Sat Aug 30 21:46:58 2025 - received message 0 from emperor
2025-08-30 21:46:58 SIGINT/SIGTERM received...killing workers...
2025-08-30 21:46:59 worker 1 buried after 1 seconds
2025-08-30 21:46:59 goodbye to uWSGI.
2025-08-30 21:46:59 VACUUM: unix socket /var/sockets/zeyadhoussainy.pythonanywhere.com/socket removed.
2025-08-30 21:47:05 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:47:04 2025] ***
2025-08-30 21:47:05 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:47:05 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:47:05 nodename: green-liveweb41
2025-08-30 21:47:05 machine: x86_64
2025-08-30 21:47:05 clock source: unix
2025-08-30 21:47:05 pcre jit disabled
2025-08-30 21:47:05 detected number of CPU cores: 4
2025-08-30 21:47:05 current working directory: /home/zeyadhoussainy
2025-08-30 21:47:05 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:47:05 *** dumping internal routing table ***
2025-08-30 21:47:05 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:47:05 *** end of the internal routing table ***
2025-08-30 21:47:05 chdir() to /home/zeyadhoussainy/
2025-08-30 21:47:05 your processes number limit is 256
2025-08-30 21:47:05 your memory page size is 4096 bytes
2025-08-30 21:47:05 detected max file descriptor number: 123456
2025-08-30 21:47:05 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:47:05 1516 entry found
2025-08-30 21:47:05 lock engine: pthread robust mutexes
2025-08-30 21:47:05 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:47:05 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 21:47:05 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:47:05 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:47:05 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:47:05 Python main interpreter initialized at 0x77262c1bcab0
2025-08-30 21:47:05 python threads support enabled
2025-08-30 21:47:05 your server socket listen backlog is limited to 100 connections
2025-08-30 21:47:05 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:47:05 setting request body buffering size to 65536 bytes
2025-08-30 21:47:05 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 21:47:05 *** Operational MODE: single process ***
2025-08-30 21:47:05 initialized 38 metrics
2025-08-30 21:47:05 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x77262c1bcab0 pid: 1 (default app)
2025-08-30 21:47:05 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:47:05 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 21:47:05 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 21:47:05 metrics collector thread started
2025-08-30 21:47:05 spawned 2 offload threads for uWSGI worker 1
2025-08-30 21:47:05 announcing my loyalty to the Emperor...
2025-08-30 21:47:06 Sat Aug 30 21:47:06 2025 - *** /var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py has been touched... grace them all !!! ***
2025-08-30 21:47:06 ...gracefully killing workers...
2025-08-30 21:47:06 Gracefully killing worker 1 (pid: 2)...
2025-08-30 21:47:07 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:47:07 2025] ***
2025-08-30 21:47:07 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:47:07 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:47:07 nodename: green-liveweb41
2025-08-30 21:47:07 machine: x86_64
2025-08-30 21:47:07 clock source: unix
2025-08-30 21:47:07 pcre jit disabled
2025-08-30 21:47:07 detected number of CPU cores: 4
2025-08-30 21:47:07 current working directory: /home/zeyadhoussainy
2025-08-30 21:47:07 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:47:07 *** dumping internal routing table ***
2025-08-30 21:47:07 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:47:07 *** end of the internal routing table ***
2025-08-30 21:47:07 chdir() to /home/zeyadhoussainy/
2025-08-30 21:47:07 your processes number limit is 256
2025-08-30 21:47:07 your memory page size is 4096 bytes
2025-08-30 21:47:07 detected max file descriptor number: 123456
2025-08-30 21:47:07 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:47:07 1516 entry found
2025-08-30 21:47:07 lock engine: pthread robust mutexes
2025-08-30 21:47:07 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:47:07 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 8
2025-08-30 21:47:07 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:47:07 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:47:07 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:47:07 Python main interpreter initialized at 0x78a4d19b6ab0
2025-08-30 21:47:07 python threads support enabled
2025-08-30 21:47:07 your server socket listen backlog is limited to 100 connections
2025-08-30 21:47:07 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:47:07 setting request body buffering size to 65536 bytes
2025-08-30 21:47:07 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 21:47:07 *** Operational MODE: single process ***
2025-08-30 21:47:07 initialized 38 metrics
2025-08-30 21:47:07 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x78a4d19b6ab0 pid: 1 (default app)
2025-08-30 21:47:07 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:47:07 spawned uWSGI master process (pid: 1)
2025-08-30 21:47:07 spawned uWSGI worker 1 (pid: 7, cores: 1)
2025-08-30 21:47:07 metrics collector thread started
2025-08-30 21:47:07 spawned 2 offload threads for uWSGI worker 1
2025-08-30 21:47:10 Sat Aug 30 21:47:10 2025 - *** /var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py has been touched... grace them all !!! ***
2025-08-30 21:47:10 ...gracefully killing workers...
2025-08-30 21:47:10 Gracefully killing worker 1 (pid: 7)...
2025-08-30 21:47:19 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:47:18 2025] ***
2025-08-30 21:47:19 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:47:19 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:47:19 nodename: green-liveweb41
2025-08-30 21:47:19 machine: x86_64
2025-08-30 21:47:19 clock source: unix
2025-08-30 21:47:19 pcre jit disabled
2025-08-30 21:47:19 detected number of CPU cores: 4
2025-08-30 21:47:19 current working directory: /home/zeyadhoussainy
2025-08-30 21:47:19 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:47:19 *** dumping internal routing table ***
2025-08-30 21:47:19 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:47:19 *** end of the internal routing table ***
2025-08-30 21:47:19 chdir() to /home/zeyadhoussainy/
2025-08-30 21:47:19 your processes number limit is 256
2025-08-30 21:47:19 your memory page size is 4096 bytes
2025-08-30 21:47:19 detected max file descriptor number: 123456
2025-08-30 21:47:19 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:47:19 1516 entry found
2025-08-30 21:47:19 lock engine: pthread robust mutexes
2025-08-30 21:47:19 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:47:19 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 21:47:19 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:47:19 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:47:19 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:47:19 Python main interpreter initialized at 0x7f5b78958ab0
2025-08-30 21:47:19 python threads support enabled
2025-08-30 21:47:19 your server socket listen backlog is limited to 100 connections
2025-08-30 21:47:19 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:47:19 setting request body buffering size to 65536 bytes
2025-08-30 21:47:19 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 21:47:19 *** Operational MODE: single process ***
2025-08-30 21:47:19 initialized 38 metrics
2025-08-30 21:47:19 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f5b78958ab0 pid: 1 (default app)
2025-08-30 21:47:19 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:47:19 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 21:47:19 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 21:47:19 metrics collector thread started
2025-08-30 21:47:19 spawned 2 offload threads for uWSGI worker 1
2025-08-30 21:58:52 Sat Aug 30 21:58:52 2025 - *** /var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py has been touched... grace them all !!! ***
2025-08-30 21:58:52 ...gracefully killing workers...
2025-08-30 21:58:52 Gracefully killing worker 1 (pid: 2)...
2025-08-30 21:58:54 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:58:53 2025] ***
2025-08-30 21:58:54 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:58:54 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:58:54 nodename: green-liveweb41
2025-08-30 21:58:54 machine: x86_64
2025-08-30 21:58:54 clock source: unix
2025-08-30 21:58:54 pcre jit disabled
2025-08-30 21:58:54 detected number of CPU cores: 4
2025-08-30 21:58:54 current working directory: /home/zeyadhoussainy
2025-08-30 21:58:54 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:58:54 *** dumping internal routing table ***
2025-08-30 21:58:54 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:58:54 *** end of the internal routing table ***
2025-08-30 21:58:54 chdir() to /home/zeyadhoussainy/
2025-08-30 21:58:54 your processes number limit is 256
2025-08-30 21:58:54 your memory page size is 4096 bytes
2025-08-30 21:58:54 detected max file descriptor number: 123456
2025-08-30 21:58:54 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:58:54 1516 entry found
2025-08-30 21:58:54 lock engine: pthread robust mutexes
2025-08-30 21:58:54 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:58:54 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 8
2025-08-30 21:58:54 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:58:54 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:58:54 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:58:54 Python main interpreter initialized at 0x7092ed59cab0
2025-08-30 21:58:54 python threads support enabled
2025-08-30 21:58:54 your server socket listen backlog is limited to 100 connections
2025-08-30 21:58:54 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:58:54 setting request body buffering size to 65536 bytes
2025-08-30 21:58:54 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 21:58:54 *** Operational MODE: single process ***
2025-08-30 21:58:54 initialized 38 metrics
2025-08-30 21:58:54 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7092ed59cab0 pid: 1 (default app)
2025-08-30 21:58:54 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:58:54 spawned uWSGI master process (pid: 1)
2025-08-30 21:58:54 spawned uWSGI worker 1 (pid: 7, cores: 1)
2025-08-30 21:58:54 metrics collector thread started
2025-08-30 21:58:54 spawned 2 offload threads for uWSGI worker 1
2025-08-30 21:59:02 Sat Aug 30 21:59:02 2025 - *** /etc/uwsgi/zeyadhoussainy.pythonanywhere.com.ini has been touched... grace them all !!! ***
2025-08-30 21:59:02 ...gracefully killing workers...
2025-08-30 21:59:02 Gracefully killing worker 1 (pid: 7)...
2025-08-30 21:59:07 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 21:59:07 2025] ***
2025-08-30 21:59:07 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 21:59:07 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 21:59:07 nodename: green-liveweb41
2025-08-30 21:59:07 machine: x86_64
2025-08-30 21:59:07 clock source: unix
2025-08-30 21:59:07 pcre jit disabled
2025-08-30 21:59:07 detected number of CPU cores: 4
2025-08-30 21:59:07 current working directory: /home/zeyadhoussainy
2025-08-30 21:59:07 detected binary path: /usr/local/bin/uwsgi
2025-08-30 21:59:07 *** dumping internal routing table ***
2025-08-30 21:59:07 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 21:59:07 *** end of the internal routing table ***
2025-08-30 21:59:07 chdir() to /home/zeyadhoussainy/alx-BE-graduation-project-ECommerce/
2025-08-30 21:59:07 your processes number limit is 256
2025-08-30 21:59:07 your memory page size is 4096 bytes
2025-08-30 21:59:07 detected max file descriptor number: 123456
2025-08-30 21:59:07 building mime-types dictionary from file /etc/mime.types...
2025-08-30 21:59:07 1516 entry found
2025-08-30 21:59:07 lock engine: pthread robust mutexes
2025-08-30 21:59:07 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 21:59:07 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 21:59:07 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 21:59:07 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 21:59:07 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 21:59:07 Python main interpreter initialized at 0x789001413ab0
2025-08-30 21:59:07 python threads support enabled
2025-08-30 21:59:07 your server socket listen backlog is limited to 100 connections
2025-08-30 21:59:07 your mercy for graceful operations on workers is 60 seconds
2025-08-30 21:59:07 setting request body buffering size to 65536 bytes
2025-08-30 21:59:07 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 21:59:07 *** Operational MODE: single process ***
2025-08-30 21:59:07 initialized 38 metrics
2025-08-30 21:59:07 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x789001413ab0 pid: 1 (default app)
2025-08-30 21:59:07 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 21:59:07 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 21:59:07 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 21:59:07 metrics collector thread started
2025-08-30 21:59:07 spawned 2 offload threads for uWSGI worker 1
2025-08-30 21:59:08 announcing my loyalty to the Emperor...
2025-08-30 22:05:38 Sat Aug 30 22:05:38 2025 - received message 0 from emperor
2025-08-30 22:05:38 SIGINT/SIGTERM received...killing workers...
2025-08-30 22:05:39 worker 1 buried after 1 seconds
2025-08-30 22:05:39 goodbye to uWSGI.
2025-08-30 22:05:39 VACUUM: unix socket /var/sockets/zeyadhoussainy.pythonanywhere.com/socket removed.
2025-08-30 22:05:44 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 22:05:43 2025] ***
2025-08-30 22:05:44 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 22:05:44 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 22:05:44 nodename: green-liveweb41
2025-08-30 22:05:44 machine: x86_64
2025-08-30 22:05:44 clock source: unix
2025-08-30 22:05:44 pcre jit disabled
2025-08-30 22:05:44 detected number of CPU cores: 4
2025-08-30 22:05:44 current working directory: /home/zeyadhoussainy
2025-08-30 22:05:44 detected binary path: /usr/local/bin/uwsgi
2025-08-30 22:05:44 *** dumping internal routing table ***
2025-08-30 22:05:44 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 22:05:44 *** end of the internal routing table ***
2025-08-30 22:05:44 chdir() to /home/zeyadhoussainy/alx-BE-graduation-project-ECommerce/
2025-08-30 22:05:44 your processes number limit is 256
2025-08-30 22:05:44 your memory page size is 4096 bytes
2025-08-30 22:05:44 detected max file descriptor number: 123456
2025-08-30 22:05:44 building mime-types dictionary from file /etc/mime.types...
2025-08-30 22:05:44 1516 entry found
2025-08-30 22:05:44 lock engine: pthread robust mutexes
2025-08-30 22:05:44 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 22:05:44 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 22:05:44 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 22:05:44 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 22:05:44 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 22:05:44 Python main interpreter initialized at 0x796d142b8ab0
2025-08-30 22:05:44 python threads support enabled
2025-08-30 22:05:44 your server socket listen backlog is limited to 100 connections
2025-08-30 22:05:44 your mercy for graceful operations on workers is 60 seconds
2025-08-30 22:05:44 setting request body buffering size to 65536 bytes
2025-08-30 22:05:44 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 22:05:44 *** Operational MODE: single process ***
2025-08-30 22:05:44 initialized 38 metrics
2025-08-30 22:05:44 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x796d142b8ab0 pid: 1 (default app)
2025-08-30 22:05:44 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 22:05:44 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 22:05:44 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 22:05:44 metrics collector thread started
2025-08-30 22:05:44 spawned 2 offload threads for uWSGI worker 1
2025-08-30 22:07:58 Sat Aug 30 22:07:58 2025 - received message 0 from emperor
2025-08-30 22:07:58 SIGINT/SIGTERM received...killing workers...
2025-08-30 22:07:59 worker 1 buried after 1 seconds
2025-08-30 22:07:59 goodbye to uWSGI.
2025-08-30 22:07:59 VACUUM: unix socket /var/sockets/zeyadhoussainy.pythonanywhere.com/socket removed.
2025-08-30 22:08:05 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 22:08:05 *** Operational MODE: single process ***
2025-08-30 22:08:05 initialized 38 metrics
2025-08-30 22:08:05 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7be65a7f3ab0 pid: 1 (default app)
2025-08-30 22:08:05 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 22:08:05 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 22:08:05 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 22:08:05 metrics collector thread started
2025-08-30 22:08:05 spawned 2 offload threads for uWSGI worker 1
2025-08-30 22:08:05 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 22:08:04 2025] ***
2025-08-30 22:08:05 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 22:08:05 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 22:08:05 nodename: green-liveweb41
2025-08-30 22:08:05 machine: x86_64
2025-08-30 22:08:05 clock source: unix
2025-08-30 22:08:05 pcre jit disabled
2025-08-30 22:08:05 detected number of CPU cores: 4
2025-08-30 22:08:05 current working directory: /home/zeyadhoussainy
2025-08-30 22:08:05 detected binary path: /usr/local/bin/uwsgi
2025-08-30 22:08:05 *** dumping internal routing table ***
2025-08-30 22:08:05 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 22:08:05 *** end of the internal routing table ***
2025-08-30 22:08:05 chdir() to /home/zeyadhoussainy/alx-BE-graduation-project-ECommerce/
2025-08-30 22:08:05 your processes number limit is 256
2025-08-30 22:08:05 your memory page size is 4096 bytes
2025-08-30 22:08:05 detected max file descriptor number: 123456
2025-08-30 22:08:05 building mime-types dictionary from file /etc/mime.types...
2025-08-30 22:08:05 1516 entry found
2025-08-30 22:08:05 lock engine: pthread robust mutexes
2025-08-30 22:08:05 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 22:08:05 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 22:08:05 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 22:08:05 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 22:08:05 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 22:08:05 Python main interpreter initialized at 0x7be65a7f3ab0
2025-08-30 22:08:05 python threads support enabled
2025-08-30 22:08:05 your server socket listen backlog is limited to 100 connections
2025-08-30 22:08:05 your mercy for graceful operations on workers is 60 seconds
2025-08-30 22:08:05 setting request body buffering size to 65536 bytes
2025-08-30 22:08:05 announcing my loyalty to the Emperor...
2025-08-30 22:16:59 Sat Aug 30 22:16:59 2025 - received message 0 from emperor
2025-08-30 22:16:59 SIGINT/SIGTERM received...killing workers...
2025-08-30 22:17:00 worker 1 buried after 1 seconds
2025-08-30 22:17:00 goodbye to uWSGI.
2025-08-30 22:17:00 unlink(): No such file or directory [core/uwsgi.c line 1654]
2025-08-30 22:19:06 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 22:19:06 2025] ***
2025-08-30 22:19:06 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 22:19:06 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 22:19:06 nodename: green-liveweb12
2025-08-30 22:19:06 machine: x86_64
2025-08-30 22:19:06 clock source: unix
2025-08-30 22:19:06 pcre jit disabled
2025-08-30 22:19:06 detected number of CPU cores: 4
2025-08-30 22:19:06 current working directory: /home/zeyadhoussainy
2025-08-30 22:19:06 detected binary path: /usr/local/bin/uwsgi
2025-08-30 22:19:06 *** dumping internal routing table ***
2025-08-30 22:19:06 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 22:19:06 *** end of the internal routing table ***
2025-08-30 22:19:06 chdir() to /home/zeyadhoussainy/
2025-08-30 22:19:06 your processes number limit is 256
2025-08-30 22:19:06 your memory page size is 4096 bytes
2025-08-30 22:19:06 detected max file descriptor number: 123456
2025-08-30 22:19:06 building mime-types dictionary from file /etc/mime.types...
2025-08-30 22:19:06 1516 entry found
2025-08-30 22:19:06 lock engine: pthread robust mutexes
2025-08-30 22:19:06 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 22:19:06 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 22:19:06 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 22:19:06 Python main interpreter initialized at 0x7f11b2a68ab0
2025-08-30 22:19:06 python threads support enabled
2025-08-30 22:19:06 your server socket listen backlog is limited to 100 connections
2025-08-30 22:19:06 your mercy for graceful operations on workers is 60 seconds
2025-08-30 22:19:06 setting request body buffering size to 65536 bytes
2025-08-30 22:19:06 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 22:19:06 *** Operational MODE: single process ***
2025-08-30 22:19:06 initialized 38 metrics
2025-08-30 22:19:06 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f11b2a68ab0 pid: 1 (default app)
2025-08-30 22:19:06 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 22:19:06 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 22:19:06 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 22:19:06 metrics collector thread started
2025-08-30 22:19:06 spawned 2 offload threads for uWSGI worker 1
2025-08-30 22:19:10 announcing my loyalty to the Emperor...
2025-08-30 22:27:41 Sat Aug 30 22:27:41 2025 - *** /var/www/zeyadhoussainy_pythonanywhere_com_wsgi.py has been touched... grace them all !!! ***
2025-08-30 22:27:41 ...gracefully killing workers...
2025-08-30 22:27:41 Gracefully killing worker 1 (pid: 2)...
2025-08-30 22:27:42 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 22:27:42 2025] ***
2025-08-30 22:27:42 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 22:27:42 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 22:27:42 nodename: green-liveweb12
2025-08-30 22:27:42 machine: x86_64
2025-08-30 22:27:42 clock source: unix
2025-08-30 22:27:42 pcre jit disabled
2025-08-30 22:27:42 detected number of CPU cores: 4
2025-08-30 22:27:42 current working directory: /home/zeyadhoussainy
2025-08-30 22:27:42 detected binary path: /usr/local/bin/uwsgi
2025-08-30 22:27:42 *** dumping internal routing table ***
2025-08-30 22:27:42 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 22:27:42 *** end of the internal routing table ***
2025-08-30 22:27:42 chdir() to /home/zeyadhoussainy/
2025-08-30 22:27:42 your processes number limit is 256
2025-08-30 22:27:42 your memory page size is 4096 bytes
2025-08-30 22:27:42 detected max file descriptor number: 123456
2025-08-30 22:27:42 building mime-types dictionary from file /etc/mime.types...
2025-08-30 22:27:42 1516 entry found
2025-08-30 22:27:42 lock engine: pthread robust mutexes
2025-08-30 22:27:42 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 22:27:42 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 8
2025-08-30 22:27:42 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 22:27:42 Python main interpreter initialized at 0x751477914ab0
2025-08-30 22:27:42 python threads support enabled
2025-08-30 22:27:42 your server socket listen backlog is limited to 100 connections
2025-08-30 22:27:42 your mercy for graceful operations on workers is 60 seconds
2025-08-30 22:27:42 setting request body buffering size to 65536 bytes
2025-08-30 22:27:42 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 22:27:42 *** Operational MODE: single process ***
2025-08-30 22:27:42 initialized 38 metrics
2025-08-30 22:27:42 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x751477914ab0 pid: 1 (default app)
2025-08-30 22:27:42 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 22:27:42 spawned uWSGI master process (pid: 1)
2025-08-30 22:27:42 spawned uWSGI worker 1 (pid: 7, cores: 1)
2025-08-30 22:27:42 metrics collector thread started
2025-08-30 22:27:42 spawned 2 offload threads for uWSGI worker 1
2025-08-30 22:27:54 Sat Aug 30 22:27:54 2025 - *** /etc/uwsgi/zeyadhoussainy.pythonanywhere.com.ini has been touched... grace them all !!! ***
2025-08-30 22:27:54 ...gracefully killing workers...
2025-08-30 22:27:54 Gracefully killing worker 1 (pid: 7)...
2025-08-30 22:27:59 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 22:27:58 2025] ***
2025-08-30 22:27:59 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 22:27:59 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 22:27:59 nodename: green-liveweb12
2025-08-30 22:27:59 machine: x86_64
2025-08-30 22:27:59 clock source: unix
2025-08-30 22:27:59 pcre jit disabled
2025-08-30 22:27:59 detected number of CPU cores: 4
2025-08-30 22:27:59 current working directory: /home/zeyadhoussainy
2025-08-30 22:27:59 detected binary path: /usr/local/bin/uwsgi
2025-08-30 22:27:59 *** dumping internal routing table ***
2025-08-30 22:27:59 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 22:27:59 *** end of the internal routing table ***
2025-08-30 22:27:59 chdir() to /home/zeyadhoussainy/
2025-08-30 22:27:59 your processes number limit is 256
2025-08-30 22:27:59 your memory page size is 4096 bytes
2025-08-30 22:27:59 detected max file descriptor number: 123456
2025-08-30 22:27:59 building mime-types dictionary from file /etc/mime.types...
2025-08-30 22:27:59 1516 entry found
2025-08-30 22:27:59 lock engine: pthread robust mutexes
2025-08-30 22:27:59 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 22:27:59 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 22:27:59 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 22:27:59 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 22:27:59 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 22:27:59 Python main interpreter initialized at 0x7aa740ce2ab0
2025-08-30 22:27:59 python threads support enabled
2025-08-30 22:27:59 your server socket listen backlog is limited to 100 connections
2025-08-30 22:27:59 your mercy for graceful operations on workers is 60 seconds
2025-08-30 22:27:59 setting request body buffering size to 65536 bytes
2025-08-30 22:27:59 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 22:27:59 *** Operational MODE: single process ***
2025-08-30 22:27:59 initialized 38 metrics
2025-08-30 22:27:59 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7aa740ce2ab0 pid: 1 (default app)
2025-08-30 22:27:59 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 22:27:59 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 22:27:59 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 22:27:59 metrics collector thread started
2025-08-30 22:27:59 spawned 2 offload threads for uWSGI worker 1
2025-08-30 22:28:56 Sat Aug 30 22:28:56 2025 - received message 0 from emperor
2025-08-30 22:28:56 SIGINT/SIGTERM received...killing workers...
2025-08-30 22:28:57 worker 1 buried after 1 seconds
2025-08-30 22:28:57 goodbye to uWSGI.
2025-08-30 22:28:57 VACUUM: unix socket /var/sockets/zeyadhoussainy.pythonanywhere.com/socket removed.
2025-08-30 22:29:01 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 22:29:01 2025] ***
2025-08-30 22:29:01 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 22:29:01 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 22:29:01 nodename: green-liveweb12
2025-08-30 22:29:01 machine: x86_64
2025-08-30 22:29:01 clock source: unix
2025-08-30 22:29:01 pcre jit disabled
2025-08-30 22:29:01 detected number of CPU cores: 4
2025-08-30 22:29:01 current working directory: /home/zeyadhoussainy
2025-08-30 22:29:01 detected binary path: /usr/local/bin/uwsgi
2025-08-30 22:29:01 *** dumping internal routing table ***
2025-08-30 22:29:01 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 22:29:01 *** end of the internal routing table ***
2025-08-30 22:29:01 chdir() to /home/zeyadhoussainy/
2025-08-30 22:29:01 your processes number limit is 256
2025-08-30 22:29:01 your memory page size is 4096 bytes
2025-08-30 22:29:01 detected max file descriptor number: 123456
2025-08-30 22:29:01 building mime-types dictionary from file /etc/mime.types...
2025-08-30 22:29:01 1516 entry found
2025-08-30 22:29:01 lock engine: pthread robust mutexes
2025-08-30 22:29:01 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 22:29:01 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 22:29:01 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 22:29:01 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 22:29:01 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 22:29:01 Python main interpreter initialized at 0x7eda3f3e4ab0
2025-08-30 22:29:01 python threads support enabled
2025-08-30 22:29:01 your server socket listen backlog is limited to 100 connections
2025-08-30 22:29:01 your mercy for graceful operations on workers is 60 seconds
2025-08-30 22:29:01 setting request body buffering size to 65536 bytes
2025-08-30 22:29:01 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 22:29:01 *** Operational MODE: single process ***
2025-08-30 22:29:01 initialized 38 metrics
2025-08-30 22:29:01 WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7eda3f3e4ab0 pid: 1 (default app)
2025-08-30 22:29:01 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 22:29:01 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 22:29:01 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 22:29:01 metrics collector thread started
2025-08-30 22:29:01 spawned 2 offload threads for uWSGI worker 1
2025-08-30 22:29:02 announcing my loyalty to the Emperor...
2025-08-30 22:44:28 Sat Aug 30 22:44:28 2025 - received message 0 from emperor
2025-08-30 22:44:28 SIGINT/SIGTERM received...killing workers...
2025-08-30 22:44:29 worker 1 buried after 1 seconds
2025-08-30 22:44:29 goodbye to uWSGI.
2025-08-30 22:44:29 VACUUM: unix socket /var/sockets/zeyadhoussainy.pythonanywhere.com/socket removed.
2025-08-30 22:44:34 *** Starting uWSGI 2.0.28 (64bit) on [Sat Aug 30 22:44:33 2025] ***
2025-08-30 22:44:34 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-30 22:44:34 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-30 22:44:34 nodename: green-liveweb12
2025-08-30 22:44:34 machine: x86_64
2025-08-30 22:44:34 clock source: unix
2025-08-30 22:44:34 pcre jit disabled
2025-08-30 22:44:34 detected number of CPU cores: 4
2025-08-30 22:44:34 current working directory: /home/zeyadhoussainy
2025-08-30 22:44:34 detected binary path: /usr/local/bin/uwsgi
2025-08-30 22:44:34 *** dumping internal routing table ***
2025-08-30 22:44:34 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-30 22:44:34 *** end of the internal routing table ***
2025-08-30 22:44:34 chdir() to /home/zeyadhoussainy/
2025-08-30 22:44:34 your processes number limit is 256
2025-08-30 22:44:34 your memory page size is 4096 bytes
2025-08-30 22:44:34 detected max file descriptor number: 123456
2025-08-30 22:44:34 building mime-types dictionary from file /etc/mime.types...
2025-08-30 22:44:34 1516 entry found
2025-08-30 22:44:34 lock engine: pthread robust mutexes
2025-08-30 22:44:34 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-30 22:44:34 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-30 22:44:34 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-30 22:44:34 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-30 22:44:34 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-30 22:44:34 Python main interpreter initialized at 0x740370e91ab0
2025-08-30 22:44:34 python threads support enabled
2025-08-30 22:44:34 your server socket listen backlog is limited to 100 connections
2025-08-30 22:44:34 your mercy for graceful operations on workers is 60 seconds
2025-08-30 22:44:34 setting request body buffering size to 65536 bytes
2025-08-30 22:44:34 mapped 334256 bytes (326 KB) for 1 cores
2025-08-30 22:44:34 *** Operational MODE: single process ***
2025-08-30 22:44:34 initialized 38 metrics
2025-08-30 22:44:34 WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x740370e91ab0 pid: 1 (default app)
2025-08-30 22:44:34 *** uWSGI is running in multiple interpreter mode ***
2025-08-30 22:44:34 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-30 22:44:34 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-30 22:44:34 metrics collector thread started
2025-08-30 22:44:34 spawned 2 offload threads for uWSGI worker 1
2025-08-31 07:38:04 Sun Aug 31 07:38:04 2025 - received message 0 from emperor
2025-08-31 07:38:04 SIGINT/SIGTERM received...killing workers...
2025-08-31 07:38:05 worker 1 buried after 1 seconds
2025-08-31 07:38:05 goodbye to uWSGI.
2025-08-31 07:38:05 VACUUM: unix socket /var/sockets/zeyadhoussainy.pythonanywhere.com/socket removed.
2025-08-31 07:38:13 *** Starting uWSGI 2.0.28 (64bit) on [Sun Aug 31 07:38:11 2025] ***
2025-08-31 07:38:13 compiled with version: 11.4.0 on 16 January 2025 20:41:13
2025-08-31 07:38:13 os: Linux-6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024
2025-08-31 07:38:13 nodename: green-liveweb12
2025-08-31 07:38:13 machine: x86_64
2025-08-31 07:38:13 clock source: unix
2025-08-31 07:38:13 pcre jit disabled
2025-08-31 07:38:13 detected number of CPU cores: 4
2025-08-31 07:38:13 current working directory: /home/zeyadhoussainy
2025-08-31 07:38:13 detected binary path: /usr/local/bin/uwsgi
2025-08-31 07:38:13 *** dumping internal routing table ***
2025-08-31 07:38:13 [rule: 0] subject: path_info regexp: \.svgz$ action: addheader:Content-Encoding:gzip
2025-08-31 07:38:13 *** end of the internal routing table ***
2025-08-31 07:38:13 chdir() to /home/zeyadhoussainy/
2025-08-31 07:38:13 your processes number limit is 256
2025-08-31 07:38:13 your memory page size is 4096 bytes
2025-08-31 07:38:13 detected max file descriptor number: 123456
2025-08-31 07:38:13 building mime-types dictionary from file /etc/mime.types...
2025-08-31 07:38:13 1516 entry found
2025-08-31 07:38:13 lock engine: pthread robust mutexes
2025-08-31 07:38:13 thunder lock: disabled (you can enable it with --thunder-lock)
2025-08-31 07:38:13 uwsgi socket 0 bound to UNIX address /var/sockets/zeyadhoussainy.pythonanywhere.com/socket fd 3
2025-08-31 07:38:13 Python version: 3.13.1 (main, Jan 16 2025, 13:50:41) [GCC 11.4.0]
2025-08-31 07:38:13 PEP 405 virtualenv detected: /home/zeyadhoussainy/venv
2025-08-31 07:38:13 Set PythonHome to /home/zeyadhoussainy/venv
2025-08-31 07:38:13 Python main interpreter initialized at 0x72b90783fab0
2025-08-31 07:38:13 python threads support enabled
2025-08-31 07:38:13 your server socket listen backlog is limited to 100 connections
2025-08-31 07:38:13 your mercy for graceful operations on workers is 60 seconds
2025-08-31 07:38:13 setting request body buffering size to 65536 bytes
2025-08-31 07:38:13 mapped 334256 bytes (326 KB) for 1 cores
2025-08-31 07:38:13 *** Operational MODE: single process ***
2025-08-31 07:38:13 initialized 38 metrics
2025-08-31 07:38:13 WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x72b90783fab0 pid: 1 (default app)
2025-08-31 07:38:13 *** uWSGI is running in multiple interpreter mode ***
2025-08-31 07:38:13 gracefully (RE)spawned uWSGI master process (pid: 1)
2025-08-31 07:38:13 spawned uWSGI worker 1 (pid: 2, cores: 1)
2025-08-31 07:38:13 metrics collector thread started
2025-08-31 07:38:13 spawned 2 offload threads for uWSGI worker 1
2025-08-31 07:38:13 announcing my loyalty to the Emperor...